### ISSUE TITLE
Comparison with leiningen and comparative examples ?

### ISSUE THREAD

**Issue by sandys** [liebke/cljr#1]
hi,
   could you do a comparison with leiningen ? Most of clojure's better known projects (leiningen, -> compojure <-, ring, cascalog) use lein as their default management tool. Could you give similar bootstrap examples for these tools as well ?

**Comment by liebke** [comment]
clj uses Leiningen as the underlying mechanism for package dependency management. The primary difference is that lein is project-oriented, and clj installs all packages in a single global repository in your home directory called .clj. The goal of clj is not to replace lein, but rather to complement it, and the two approaches can happily coexist.

I'm not sure I understand your request for bootstrap examples, can you clarify?

**Comment by sandys** [comment]
thanks for the clarification - my bootstrap examples meant how to setup a compojure app using clj, etc etc.

**Comment by liebke** [comment]
I think the overview section of the README now provides a basic comparison between cljr and lein.
