### ISSUE TITLE
Missing cygwin support

### ISSUE THREAD

**Issue by mchampine** [liebke/cljr#10]
classpath does not appear to get set correctly on cygwin. 

<pre>
$ cljr list
Exception in thread "main" java.lang.NoClassDefFoundError: cljr/App
..etc..

$ cljr repl
Exception in thread "main" java.lang.NoClassDefFoundError: jline/ConsoleRunner
..etc..
</pre>

Maybe something like

<pre>
cygwin=false
case "`uname`" in
  CYGWIN*) cygwin=true;;
esac
</pre>

test

<pre>
if $cygwin; then 
     cygwin cmds 
else 
    unix/linux cmds
fi
</pre>

cygwin versions of classpath setting statements.

<pre>
  CLASSPATH="src;test;."
  CLASSPATH="$CLASSPATH"\;"$CLJR_HOME"/cljr.jar
  CLASSPATH="$CLASSPATH"\;$f  (2 places)
</pre>

**Comment by liebke** [comment]
I've pushed an update that should resolve this. When the cljr shell script is generated on a platform that use ';' as path-separator, it will be rendered as \;.

I'm not running Cygwin, so please let me know if this fixes the issue or not.

David

**Comment by mchampine** [comment]
Fixed!  Tried several funtions on cygwin - list, repl, swingrepl, search, describe - all seems in order. Nice!

**Comment by liebke** [comment]
Excellent, thanks for testing it out.
