### ISSUE TITLE
cljr startup messages should print to stderr

### ISSUE THREAD

**Issue by markmfredrickson** [liebke/cljr#11]
Messages such as "Clojure classpath initialized by cljr." are printing to stdout. They should print to stderr so that they do not appear in uses like `$ cljr run foo.clj > foo.txt`

**Comment by markmfredrickson** [comment]
As a follow up, you could probably just make your own printer function, eg `(defn cljprintln [f] (with-out-writer *err* f))`

**Comment by liebke** [comment]
Just removed the message, it wasn't necessary.
