### ISSUE TITLE
Update to Clojure 1.2 RC1

### ISSUE THREAD

**Issue by rsanheim** [liebke/cljr#13]
Latest and greatest - it appears cljr uses 1.2 beta.

**Comment by liebke** [comment]
Just updated to Clojure 1.2 release.

**Comment by michel-slm** [comment]
The latest Git commit available to the public still has 1.2.0 listed in the pom, and still only installs 1.2.0 beta1. Is there an updated cljr that is, perhaps, not pushed to the public?

Also, leiningen needs to be updated to 1.3.1.
