### ISSUE TITLE
How to use a different clojure/clojure-contrib jar?

### ISSUE THREAD

**Issue by taoeffect** [liebke/cljr#4]
I'd like to work with the latest clojure.jar and clojure-contrib.jar files that I've built from their respective repos, how do I get clj to use them?

**Comment by liebke** [comment]
That isn't really possible yet, but I'm looking at adding functionality similar to Ruby's rvm.

**Comment by taoeffect** [comment]
Can't you make it so that 'clj' respects the CLOJURE_HOME environment variable?

I think we should move as a community to make that a standard. Where CLOJURE_HOME points to a directory (not ending in a '/') that contains clojure.jar and possibly clojure-contrib.jar

**Comment by liebke** [comment]
I'm not sure if I'll use the CLOJURE_HOME approach. I'm thinking more along the lines of Ruby's rvm.

**Comment by taoeffect** [comment]
OK, didn't know about rvm so I just looked it up. It seems neat, but looks complicated and like it could take a while to implement, why not support both approaches? Of course you don't have to, just curious.

**Comment by liebke** [comment]
CLOJURE_HOME option added, see options section of README.

**Comment by taoeffect** [comment]
Awesome! :-)
