### ISSUE TITLE
Paths need to be quoted in Windows

### ISSUE THREAD

**Issue by grammati** [liebke/cljr#6]
The generated clj.bat file contains -Duser.home=C:\Documents and Settings.. etc. on windows XP.  The path needs quotes.

**Comment by liebke** [comment]
Fixed, thanks for catching that.

**Comment by asdf4** [comment]
couldn't get going on mac so switched to windows.

but not fixed in the install jar.  had to do the same thing.

be sure with SET_CLASSPATH to set the end quote only since you remembered the open quote.
