### ISSUE TITLE
Allow setting java options for running REPL or SwingREPL

### ISSUE THREAD

**Issue by dakrone** [liebke/cljr#7]
I have some code I would like to test from the REPL, it requires 1gb of space allocated in order not to overflow the heap.

I'd like to be able to do something like:

export CLJ_OPTS="-server -Xmx1024m"

and have clj respect those options.

**Comment by liebke** [comment]
Excellent point, I do need to allow for jvm options.

**Comment by liebke** [comment]
JVM_OPTS option added, see options section of README.
