### ISSUE TITLE
Allow user-specified disabling of jLine

### ISSUE THREAD

**Issue by dakrone** [liebke/cljr#8]
When I run 'clj repl', I am unable to paste the characters "せん" (they show up as "??" instead). When I remove Jline from the REPL command, I can type them without a problem.

Maybe an environment variable like CLJ_ENABLE_JLINE=false or a different command like 'clj utf-repl' to spawn a REPL without jline?

**Comment by liebke** [comment]
This is a good point, I'll add the option to disable jline. Have you tried 'clj swingrepl'? I'd be curious if that works better with utf.

**Comment by dakrone** [comment]
I tried it with swingrepl, here's what I go:

user=> (str "せん")
"??"
user=> せん
\?
\?
user=> (println "せん")
??
nil

Looks like I was able to actually type the characters, which is an improvement from the regular REPL.

**Comment by liebke** [comment]
DISABLE_JLINE option added, see options section of README.
